site_name: limnd2
site_author: Laboratory Imaging s.r.o.
repo_name: limnd2
repo_url: https://github.com/Laboratory-Imaging/limnd2
site_description: A pure Python ND2 file reader and writer.

theme:
  name: material
  features:
    - navigation.expand

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_inheritance_diagram: true
            separate_members: true
            #show_if_no_docstring: true

nav:
  - Home: index.md
  - API Reference:
      - nd2.py: nd2.md
      - attributes.py: attributes.md

